name: test_python_pkg

on: [push, pull_request]

jobs:
  test_on_ubuntu_latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version_ubuntu-latest: ["3.10", 3.11]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python ${{ matrix.python-version_ubuntu-latest }}
        uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ matrix.python-version_ubuntu-latest }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install python pkgs
        run: |
          export GIT_ACTION=true
          ./install.sh

      - name: Install deps via poetry
        run: |
          venv/*/pip install poetry
          venv/*/poetry install

      - name: install pytest pytest-cov
        run: |
          venv/*/pip install pytest pytest-cov

      - name: Test with pytest
        run: |
          export COVERAGE=true
          ./test.sh
        shell: bash

  lint:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.x

      - name: install pre-commit
        run: pip install pre-commit

      - name: pre-commit cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pre-commit
          key: "${{ hashFiles('.pre-commit-config.yaml') }}"

      - run: pre-commit run --all-files --show-diff-on-failure
